<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Platforms>x64</Platforms>
        <InvariantGlobalization>true</InvariantGlobalization>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DebugType>embedded</DebugType>
        <Deterministic>true</Deterministic>
        <LangVersion>preview</LangVersion>
        <AssemblyName>NTE</AssemblyName>
        <ProductName>Neverness To Everness Plugin</ProductName>
        <Product>Collapse</Product>
        <Description>This library is a plugin for adding support for the game "Neverness To Everness" (异环) into Collapse Launcher</Description>
        <AssemblyTitle>Neverness To Everness Plugin</AssemblyTitle>
        <Company>CollapsePlugin</Company>
        <Authors>$(Company).</Authors>
        <Copyright>Copyright 2026 $(Company)</Copyright>
        <Version>1.0.0</Version>
        <ApplicationIcon>icon.ico</ApplicationIcon>
        <Configurations>Debug;Release</Configurations>
        <Title>Hi3Helper.Plugin.NTE</Title>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hi3Helper.Plugin.Core\Hi3Helper.Plugin.Core.csproj"/>
        <ProjectReference Include="..\Hi3Helper.Wanmei.Core\Hi3Helper.Wanmei.Core.csproj"/>
    </ItemGroup>

</Project>
