<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Platforms>x64</Platforms>
        <InvariantGlobalization>true</InvariantGlobalization>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DebugType>embedded</DebugType>
        <Deterministic>true</Deterministic>
        <LangVersion>preview</LangVersion>
        <AssemblyName>Wanmei.Core</AssemblyName>
        <ProductName>Wanmei (Perfect World) Core Plugin Library</ProductName>
        <Product>Collapse</Product>
        <Description>Common core functionality (Perfect World pw_sdk / PatcherSDK update mechanism) for Wanmei-published game plugins in Collapse Launcher</Description>
        <AssemblyTitle>Wanmei Core Library</AssemblyTitle>
        <Company>CollapsePlugin</Company>
        <Authors>$(Company).</Authors>
        <Copyright>Copyright 2026 $(Company)</Copyright>
        <Version>1.0.0</Version>
        <Configurations>Debug;Release</Configurations>
        <Title>Hi3Helper.Wanmei.Core</Title>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hi3Helper.Plugin.Core\Hi3Helper.Plugin.Core.csproj"/>
    </ItemGroup>

</Project>
